server.port=8081
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#order service
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://order-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/orderService/**
spring.cloud.gateway.routes[0].filters[0]=name=CircuitBreaker,args.name=orderServiceCircuitBreaker,args.fallbackUri=forward:/fallback/orderService

#inventory service
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/inventory/**
spring.cloud.gateway.routes[1].filters[0]=name=CircuitBreaker,args.name=inventoryServiceCircuitBreaker,args.fallbackUri=forward:/fallback/inventoryService

#payment service
spring.cloud.gateway.routes[2].id=payment-service
spring.cloud.gateway.routes[2].uri=lb://payment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/payment/**
spring.cloud.gateway.routes[2].filters[0]=name=CircuitBreaker,args.name=paymentServiceCircuitBreaker,args.fallbackUri=forward:/fallback/paymentService

#resilience4j configuration
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.timelimiter.configs.default.timeoutDuration=10s

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
